services:
    tailscale:
        container_name: tailscaled
        image: tailscale/tailscale:latest
        hostname: raspberrypi
        environment:
          - TS_AUTHKEY=
          - TS_ROUTES=192.168.29.0/24
          - TS_EXTRA_ARGS=--advertise-exit-node
          - TS_STATE_DIR=/var/lib/tailscale
          - TS_USERSPACE=false
        volumes:
            - ${PWD}/tailscale-varlib/state:/var/lib/tailscale
        devices:
            - /dev/net/tun:/dev/net/tun
        #network_mode: host
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        restart: unless-stopped
